package com.netflix.exhibitor.core.config.s3;

import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.model.CompleteMultipartUploadRequest;
import com.amazonaws.services.s3.model.InitiateMultipartUploadRequest;
import com.amazonaws.services.s3.model.InitiateMultipartUploadResult;
import com.amazonaws.services.s3.model.PartETag;
import com.amazonaws.services.s3.model.S3Object;
import com.amazonaws.services.s3.model.UploadPartRequest;
import com.amazonaws.services.s3.model.UploadPartResult;
import com.netflix.exhibitor.core.config.ConfigProvider;
import com.netflix.exhibitor.core.config.InstanceConfig;
import com.netflix.exhibitor.core.config.LoadedInstanceConfig;
import com.netflix.exhibitor.core.config.PropertyBasedInstanceConfig;
import com.netflix.exhibitor.core.s3.S3Client;
import com.netflix.exhibitor.core.s3.S3ClientFactory;
import com.netflix.exhibitor.core.s3.S3Credential;
import com.netflix.exhibitor.core.s3.S3Utils;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Properties;

public class S3ConfigProvider implements ConfigProvider
{
    private final S3ConfigArguments arguments;
    private final S3Client s3Client;
    private final Properties defaults;

    public S3ConfigProvider(S3ClientFactory factory, S3Credential credential, S3ConfigArguments arguments) throws Exception
    {
        this(factory, credential, arguments, new Properties());
    }

    public S3ConfigProvider(S3ClientFactory factory, S3Credential credential, S3ConfigArguments arguments, Properties defaults) throws Exception
    {
        this.arguments = arguments;
        this.defaults = defaults;
        BasicAWSCredentials credentials = new BasicAWSCredentials(credential.getAccessKeyId(), credential.getSecretAccessKey());
        s3Client = factory.makeNewClient(credentials);
    }

    @Override
    public LoadedInstanceConfig loadConfig() throws Exception
    {
        S3Object    object = s3Client.getObject(arguments.getBucket(), arguments.getKey());
        Date        lastModified = object.getObjectMetadata().getLastModified();

        Properties  properties = new Properties();
        properties.load(object.getObjectContent());

        PropertyBasedInstanceConfig config = new PropertyBasedInstanceConfig(properties, defaults);
        return new LoadedInstanceConfig(config, lastModified.getTime());
    }

    @Override
    public LoadedInstanceConfig storeConfig(InstanceConfig config, long compareLastModified) throws Exception
    {
        S3Object                        object = s3Client.getObject(arguments.getBucket(), arguments.getKey());
        Date                            lastModified = object.getObjectMetadata().getLastModified();
        if ( lastModified.getTime() != compareLastModified )
        {
            return null;    // apparently there's no atomic way to do this with S3 so this will have to do
        }

        PropertyBasedInstanceConfig     propertyBasedInstanceConfig = new PropertyBasedInstanceConfig(config);
        ByteArrayOutputStream           out = new ByteArrayOutputStream();
        propertyBasedInstanceConfig.getProperties().store(out, "Auto-generated by Exhibitor");

        InitiateMultipartUploadRequest  request = new InitiateMultipartUploadRequest(arguments.getBucket(), arguments.getKey());
        InitiateMultipartUploadResult   result = s3Client.initiateMultipartUpload(request);

        byte[]                          bytes = out.toByteArray();
        byte[]                          md5 = S3Utils.md5(ByteBuffer.wrap(bytes));

        UploadPartRequest               partRequest = new UploadPartRequest();
        partRequest.setBucketName(arguments.getBucket());
        partRequest.setKey(arguments.getKey());
        partRequest.setUploadId(result.getUploadId());
        partRequest.setPartNumber(0);
        partRequest.setPartSize(bytes.length);
        partRequest.setMd5Digest(S3Utils.toBase64(md5));
        partRequest.setInputStream(new ByteArrayInputStream(bytes));

        UploadPartResult                partResult = s3Client.uploadPart(partRequest);
        if ( !partResult.getPartETag().getETag().equals(S3Utils.toHex(md5)) )
        {
            throw new Exception("Unable to match MD5 for config");
        }

        List<PartETag>                  partETags = Arrays.asList(partResult.getPartETag());
        CompleteMultipartUploadRequest completeRequest = new CompleteMultipartUploadRequest(arguments.getBucket(), arguments.getKey(), result.getUploadId(), partETags);
        s3Client.completeMultipartUpload(completeRequest);

        return null;
    }
}
