package com.netflix.exhibitor.core.config.filesystem;

import com.google.common.io.Closeables;
import com.netflix.exhibitor.core.config.ConfigProvider;
import com.netflix.exhibitor.core.config.InstanceConfig;
import com.netflix.exhibitor.core.config.LoadedInstanceConfig;
import com.netflix.exhibitor.core.config.PropertyBasedInstanceConfig;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.RandomAccessFile;
import java.nio.channels.Channels;
import java.nio.channels.FileLock;
import java.util.Properties;

/**
 * Config provider that uses a properties file store locally
 */
public class FileSystemConfigProvider implements ConfigProvider
{
    private final File propertiesFile;
    private final Properties defaults;

    /**
     * @param propertiesFile where to store the properties
     */
    @SuppressWarnings("UnusedDeclaration")
    public FileSystemConfigProvider(File propertiesFile)
    {
        this(propertiesFile, new Properties());
    }

    /**
     * @param propertiesFile where to store the properties
     * @param defaults default values
     */
    public FileSystemConfigProvider(File propertiesFile, Properties defaults)
    {
        this.propertiesFile = propertiesFile;
        this.defaults = defaults;
    }

    @Override
    public LoadedInstanceConfig loadConfig() throws Exception
    {
        Properties      properties = new Properties();
        if ( propertiesFile.exists() )
        {
            RandomAccessFile    raf = new RandomAccessFile(propertiesFile, "rw");
            try
            {
                FileLock        lock = raf.getChannel().lock();
                try
                {
                    properties.load(Channels.newInputStream(raf.getChannel()));
                }
                finally
                {
                    lock.release();
                }
            }
            finally
            {
                Closeables.closeQuietly(raf);
            }
        }
        PropertyBasedInstanceConfig config = new PropertyBasedInstanceConfig(properties, defaults);
        return new LoadedInstanceConfig(config, propertiesFile.lastModified());
    }

    @Override
    public LoadedInstanceConfig storeConfig(InstanceConfig config, long compareLastModified) throws Exception
    {
        PropertyBasedInstanceConfig     propertyBasedInstanceConfig = new PropertyBasedInstanceConfig(config);

        long                lastModified = 0;
        FileOutputStream    fileStream = new FileOutputStream(propertiesFile);
        OutputStream        out = new BufferedOutputStream(fileStream);
        try
        {
            FileLock lock = fileStream.getChannel().lock();
            try
            {
                propertyBasedInstanceConfig.getProperties().store(out, "Auto-generated by Exhibitor");
                lastModified = propertiesFile.lastModified();
            }
            finally
            {
                lock.release();
            }
        }
        finally
        {
            Closeables.closeQuietly(out);
        }

        return new LoadedInstanceConfig(propertyBasedInstanceConfig, lastModified);
    }
}
