package com.netflix.exhibitor.config;

import com.google.common.io.Closeables;
import com.netflix.exhibitor.ConfigProvider;
import com.netflix.exhibitor.InstanceConfig;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;

public class LocalFileConfigProvider implements ConfigProvider
{
    private final File propertiesFile;
    private final PropertyBasedConfigProvider provider;

    public LocalFileConfigProvider(File propertiesFile)
    {
        this(propertiesFile, new PropertyBasedConfigProvider());
    }

    public LocalFileConfigProvider(File propertiesFile, InstanceConfig defaults)
    {
        this(propertiesFile, new PropertyBasedConfigProvider(defaults));
    }

    private LocalFileConfigProvider(File propertiesFile, PropertyBasedConfigProvider provider)
    {
        this.propertiesFile = propertiesFile;
        this.provider = provider;
    }

    @Override
    public InstanceConfig loadConfig() throws Exception
    {
        if ( propertiesFile.exists() )
        {
            Properties      properties = new Properties();
            InputStream     in = new BufferedInputStream(new FileInputStream(propertiesFile));
            try
            {
                properties.load(in);
                provider.setProperties(properties);
            }
            finally
            {
                Closeables.closeQuietly(in);
            }
        }
        return provider.loadConfig();
    }

    @Override
    public void storeConfig(InstanceConfig config) throws Exception
    {
        provider.storeConfig(config);
        OutputStream        out = new BufferedOutputStream(new FileOutputStream(propertiesFile));
        try
        {
            provider.getProperties().store(out, "Auto-generated by Exhibitor");
        }
        finally
        {
            Closeables.closeQuietly(out);
        }
    }
}
